# Generated by Django 4.2.30 on 2026-04-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-friendly label, e.g. "Production"', max_length=100)),
                ('ssh_host', models.CharField(help_text='Server IP or hostname', max_length=255)),
                ('ssh_user', models.CharField(default='root', max_length=100)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_key_path', models.CharField(default='/app/ssh_keys/id_ed25519', help_text='Path to SSH private key inside the container', max_length=500)),
                ('db_name', models.CharField(help_text='PostgreSQL database name', max_length=100)),
                ('db_user', models.CharField(default='postgres', max_length=100)),
                ('db_password', models.CharField(blank=True, help_text='Leave blank to use PGPASSWORD from environment', max_length=255)),
                ('db_container', models.CharField(blank=True, help_text='Docker container name on the remote server (e.g. markaz_db). Leave blank if PostgreSQL runs directly on the host.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('log', models.TextField(blank=True, help_text='stdout / stderr output')),
                ('triggered_by', models.CharField(choices=[('schedule', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backups.backuptarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
